const test = require("node:test"); const assert = require("node:assert/strict"); const a = require("../lib/anki.js");
test("builds API envelope", () => assert.deepEqual(a.requestBody("version"), { action: "version", version: 6, params: {} }));
test("parses Anki response", () => { assert.equal(a.parseResponse({ result: 6, error: null }), 6); assert.throws(() => a.parseResponse({ result: null, error: "bad" }), /bad/); });
test("composes only meaning and video sentence on the back", () => { const n = a.buildNote({ deckName: "D", modelName: "Basic", fieldMap: { term: "Front", cardBack: "Back" }, values: { term: "<x>", partOfSpeech: "noun", meaning: "针；尖", videoSentence: "A <x>.", videoTranslation: "一根针。", generatedExample: "The needle is sharp.", reference: "剧名 · 约 02:35" }, tags: ["one", "one"] }); assert.equal(n.fields.Front, "&lt;x&gt;"); assert.match(n.fields.Back, /^<div>针；尖<\/div>/); assert.match(n.fields.Back, /A &lt;x&gt;\.<br>译文：一根针。/); assert.doesNotMatch(n.fields.Back, /noun|The needle is sharp|约 02:35/); assert.deepEqual(n.tags, ["one"]); });
test("rejects unsupported model and mappings", () => { assert.throws(() => a.buildNote({ deckName: "", modelName: "Basic" }), /牌组/); assert.throws(() => a.buildNote({ deckName: "D", modelName: "Cloze", fieldMap: { term: "Front", cardBack: "Back" }, values: { term: "x", meaning: "m" } }), /只支持 Basic/); assert.throws(() => a.buildNote({ deckName: "D", modelName: "Basic", fieldMap: { term: "Front", cardBack: "Front" }, values: { term: "x", meaning: "m" } }), /Front 和 Back/); });
test("requires a meaning even when part of speech is present", () => { assert.throws(() => a.buildNote({ deckName: "D", modelName: "Basic", fieldMap: { term: "Front", cardBack: "Back" }, values: { term: "kept", partOfSpeech: "verb", meaning: "  " } }), /请填写释义/); });
test("does not add old grammar fields to new notes", () => { const note = a.buildNote({ deckName: "D", modelName: "Basic", fieldMap: { term: "Front", cardBack: "Back" }, values: { term: "食べました", lemma: "食べる", formNote: "过去式", usageNote: "说明", meaning: "吃" } }); assert.equal(note.fields.Front, "食べました"); assert.doesNotMatch(note.fields.Back, /原形|过去式|说明/); });
test("rejects malformed Anki envelope", () => assert.throws(() => a.parseResponse({ result: 1 }), /格式/));
test("revalidates Basic note against live card template", () => { const note = { deckName: "D", modelName: "Basic", fields: { Front: "x", Back: "y" } }; const meta = { decks: ["D"], models: ["Basic", "Cloze"], fields: ["Front", "Back"], templates: { "Card 1": [["Front"], ["Back"]] } }; assert.equal(a.validateNoteAgainstMetadata(note, meta), note); assert.throws(() => a.validateNoteAgainstMetadata(note, { ...meta, templates: { "Card 1": [["Back"], ["Front"]] } }), /模板/); assert.throws(() => a.validateNoteAgainstMetadata({ ...note, modelName: "Cloze" }, meta), /只支持 Basic/); });
